//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeazonIzy.Strings {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MeazonIzy.Strings.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.Please email us at: support @meazon.com.
        /// </summary>
        public static string a1 {
            get {
                return ResourceManager.GetString("a1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.Check your internet access and try again..
        /// </summary>
        public static string a10 {
            get {
                return ResourceManager.GetString("a10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.Internet connection is a structural element for this type of devices. However even if you dont have for a while scheduler is valid, but if you need further settings you can use windows application for on/off..
        /// </summary>
        public static string a2 {
            get {
                return ResourceManager.GetString("a2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.You can use windows app to add new plugs.To add your plug to another GW, you have to leave the current network (button/windows application) and then add this plug to a new gateway.
        /// </summary>
        public static string a3 {
            get {
                return ResourceManager.GetString("a3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.Schedule is a total of rules that the user can set via the Meazon Izy application, to turn on an Izy-plug in repeated intervals throughout the week. For example: The lights of the garden are switched on daily, at 20.00-00.00 in the evening (switched off the rest of the day)..
        /// </summary>
        public static string a4 {
            get {
                return ResourceManager.GetString("a4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.Not with Izy products. You can check Meazon&apos;s Bizy products..
        /// </summary>
        public static string a5 {
            get {
                return ResourceManager.GetString("a5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6. You can share user rights with someone by entering his email from Google or Facebook account so he can control your Izy plugs too..
        /// </summary>
        public static string a6 {
            get {
                return ResourceManager.GetString("a6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.In all countries with schuko plug connectors and unrestricted access in Google or Facebook..
        /// </summary>
        public static string a7 {
            get {
                return ResourceManager.GetString("a7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.Google and Facebook are the two main providers we use for your secure and fast entry to our system. We will use these emails only to send you email newsletters for our products..
        /// </summary>
        public static string a8 {
            get {
                return ResourceManager.GetString("a8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.Wifi Gateway has four leds which are (from left to right) : the Zigbee led, the Internet Connection led, the Wifi connection led and the Power led..
        /// </summary>
        public static string a9 {
            get {
                return ResourceManager.GetString("a9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string AccountTitle {
            get {
                return ResourceManager.GetString("AccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Coadmin .
        /// </summary>
        public static string AddAdminTitle {
            get {
                return ResourceManager.GetString("AddAdminTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddLabel {
            get {
                return ResourceManager.GetString("AddLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to example@example.com.
        /// </summary>
        public static string AdminHolder {
            get {
                return ResourceManager.GetString("AdminHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string AlertLabel {
            get {
                return ResourceManager.GetString("AlertLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Day.
        /// </summary>
        public static string AllDayLabel {
            get {
                return ResourceManager.GetString("AllDayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelLabel {
            get {
                return ResourceManager.GetString("CancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coadmins.
        /// </summary>
        public static string CoAdminsLabel {
            get {
                return ResourceManager.GetString("CoAdminsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Days.
        /// </summary>
        public static string DaysTitle {
            get {
                return ResourceManager.GetString("DaysTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Coadmin?.
        /// </summary>
        public static string DeleteAction {
            get {
                return ResourceManager.GetString("DeleteAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteLabel {
            get {
                return ResourceManager.GetString("DeleteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string DeviceLabel {
            get {
                return ResourceManager.GetString("DeviceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string DevicesTitle {
            get {
                return ResourceManager.GetString("DevicesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device has a scheduler enabled!Do you want to deactivate it?.
        /// </summary>
        public static string DisableScheduleQuestion {
            get {
                return ResourceManager.GetString("DisableScheduleQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sing Out.
        /// </summary>
        public static string DisconectLabel {
            get {
                return ResourceManager.GetString("DisconectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit CoAdmin.
        /// </summary>
        public static string EditAdminTitle {
            get {
                return ResourceManager.GetString("EditAdminTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditLabel {
            get {
                return ResourceManager.GetString("EditLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequently Asked Questions.
        /// </summary>
        public static string FaqFull {
            get {
                return ResourceManager.GetString("FaqFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string FaqLabel {
            get {
                return ResourceManager.GetString("FaqLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string FridayLabel {
            get {
                return ResourceManager.GetString("FridayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fri.
        /// </summary>
        public static string FriLabel {
            get {
                return ResourceManager.GetString("FriLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Time.
        /// </summary>
        public static string FromTimeLabel {
            get {
                return ResourceManager.GetString("FromTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralTitle {
            get {
                return ResourceManager.GetString("GeneralTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Language.
        /// </summary>
        public static string LanguageSettingsLabel {
            get {
                return ResourceManager.GetString("LanguageSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Login.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string MasterTitleAndroid {
            get {
                return ResourceManager.GetString("MasterTitleAndroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string MasterTitleWindows {
            get {
                return ResourceManager.GetString("MasterTitleWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string MondayLabel {
            get {
                return ResourceManager.GetString("MondayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon.
        /// </summary>
        public static string MonLabel {
            get {
                return ResourceManager.GetString("MonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string NoAction {
            get {
                return ResourceManager.GetString("NoAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter an email!.
        /// </summary>
        public static string NullAlert {
            get {
                return ResourceManager.GetString("NullAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OkAction {
            get {
                return ResourceManager.GetString("OkAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string OptionsLabel {
            get {
                return ResourceManager.GetString("OptionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyLabel {
            get {
                return ResourceManager.GetString("PrivacyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        public static string ProviderLabel {
            get {
                return ResourceManager.GetString("ProviderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.How do I get support? Phone number or email?.
        /// </summary>
        public static string q1 {
            get {
                return ResourceManager.GetString("q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.What does the &quot;OFFLINE&quot; indication mean?.
        /// </summary>
        public static string q10 {
            get {
                return ResourceManager.GetString("q10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.Do I need Internet connection all the time?What will happen if we have no internet connection for a while, day or more, (unpaid bill or technical problem)?.
        /// </summary>
        public static string q2 {
            get {
                return ResourceManager.GetString("q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.How do I add new Izy plugs and/or Gateways? How can I add my Izy plugs to another Gateway? How do I expand my ZigBee n/w (more plugs/GATEWAYs).
        /// </summary>
        public static string q3 {
            get {
                return ResourceManager.GetString("q3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.What is a scheduler and how do i set it up?.
        /// </summary>
        public static string q4 {
            get {
                return ResourceManager.GetString("q4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.Can I measure electricity consumption from my Izy plug?.
        /// </summary>
        public static string q5 {
            get {
                return ResourceManager.GetString("q5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.In the menu there is the choise &quot;Users&quot;. What is that for?.
        /// </summary>
        public static string q6 {
            get {
                return ResourceManager.GetString("q6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.In which countries can I use Meazon Izy plugs?.
        /// </summary>
        public static string q7 {
            get {
                return ResourceManager.GetString("q7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.Why do you need a google or facebook account? What is the policy of protecting my personal information? How will your company use this account?.
        /// </summary>
        public static string q8 {
            get {
                return ResourceManager.GetString("q8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.How can I be sure Wifi Gateway works properly every time? What are the indications?.
        /// </summary>
        public static string q9 {
            get {
                return ResourceManager.GetString("q9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string RenameTitle {
            get {
                return ResourceManager.GetString("RenameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        public static string RepeatLabel {
            get {
                return ResourceManager.GetString("RepeatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules:.
        /// </summary>
        public static string RulesLabel {
            get {
                return ResourceManager.GetString("RulesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat.
        /// </summary>
        public static string SatLabel {
            get {
                return ResourceManager.GetString("SatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string SaturdayLabel {
            get {
                return ResourceManager.GetString("SaturdayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveLabel {
            get {
                return ResourceManager.GetString("SaveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedules.
        /// </summary>
        public static string SchedulesTitle {
            get {
                return ResourceManager.GetString("SchedulesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string ScheduleTitle {
            get {
                return ResourceManager.GetString("ScheduleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Sound Notifications.
        /// </summary>
        public static string SoundLabel {
            get {
                return ResourceManager.GetString("SoundLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always override schedule.
        /// </summary>
        public static string State1 {
            get {
                return ResourceManager.GetString("State1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always ask to override.
        /// </summary>
        public static string State2 {
            get {
                return ResourceManager.GetString("State2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do nothing.
        /// </summary>
        public static string State3 {
            get {
                return ResourceManager.GetString("State3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch State Action.
        /// </summary>
        public static string StateLabel {
            get {
                return ResourceManager.GetString("StateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string SundayLabel {
            get {
                return ResourceManager.GetString("SundayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun.
        /// </summary>
        public static string SunLabel {
            get {
                return ResourceManager.GetString("SunLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu.
        /// </summary>
        public static string ThuLabel {
            get {
                return ResourceManager.GetString("ThuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string ThursdayLabel {
            get {
                return ResourceManager.GetString("ThursdayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Time.
        /// </summary>
        public static string TimeTitle {
            get {
                return ResourceManager.GetString("TimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Time.
        /// </summary>
        public static string ToTimeLabel {
            get {
                return ResourceManager.GetString("ToTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tue.
        /// </summary>
        public static string TueLabel {
            get {
                return ResourceManager.GetString("TueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string TuesdayLabel {
            get {
                return ResourceManager.GetString("TuesdayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn On.
        /// </summary>
        public static string TurnOnLabel {
            get {
                return ResourceManager.GetString("TurnOnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserNameLabel {
            get {
                return ResourceManager.GetString("UserNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string UsersTitle {
            get {
                return ResourceManager.GetString("UsersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a Valid Email!.
        /// </summary>
        public static string ValidationAlert {
            get {
                return ResourceManager.GetString("ValidationAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value:.
        /// </summary>
        public static string ValueLabel {
            get {
                return ResourceManager.GetString("ValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wed.
        /// </summary>
        public static string WedLabel {
            get {
                return ResourceManager.GetString("WedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string WednesdayLabel {
            get {
                return ResourceManager.GetString("WednesdayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Time Set!.
        /// </summary>
        public static string WrongTimeLabel {
            get {
                return ResourceManager.GetString("WrongTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesAction {
            get {
                return ResourceManager.GetString("YesAction", resourceCulture);
            }
        }
    }
}
